import React from 'react';
import { Activity, Brain, Clock3, LockKeyhole, TrendingUp } from 'lucide-react';
import { CalibrationNode, WellbeingEntry } from '../types';
import { formatEntryTime, getReadiness, getWellbeingInsights, isToday } from '../wellbeingLogic';

interface LifeSignalsProps {
  nodes: CalibrationNode[];
  history: WellbeingEntry[];
  onUpdateNode: (nodeId: string, newValue: number, record?: boolean) => void;
}

function DayGraph({ node, entries }: { node: CalibrationNode; entries: WellbeingEntry[] }) {
  const points = entries.filter(entry => entry.nodeId === node.id && isToday(entry.timestamp)).map(entry => {
    const date = new Date(entry.timestamp);
    const minute = date.getHours() * 60 + date.getMinutes();
    return `${Math.max(2, (minute / 1440) * 100)},${28 - ((entry.value - 1) / 9) * 24}`;
  });
  if (points.length === 1) points.unshift(`2,${points[0].split(',')[1]}`);
  return <div className="h-8 rounded border border-zinc-900 bg-zinc-950/70 overflow-hidden relative"><svg viewBox="0 0 100 30" preserveAspectRatio="none" className="h-full w-full"><path d="M0 15 H100" stroke="#27272a" strokeWidth="0.5" strokeDasharray="2 3" />{points.length > 1 ? <polyline points={points.join(' ')} fill="none" stroke={node.color} strokeWidth="1.8" vectorEffect="non-scaling-stroke" /> : <path d={`M2 ${28 - ((node.value - 1) / 9) * 24} H98`} stroke={node.color} strokeWidth="1" opacity="0.35" strokeDasharray="3 3" />}</svg><span className="absolute bottom-0.5 left-1 text-[6px] text-zinc-700">12A</span><span className="absolute bottom-0.5 left-1/2 text-[6px] text-zinc-700">12P</span><span className="absolute bottom-0.5 right-1 text-[6px] text-zinc-700">NOW</span></div>;
}

export default function LifeSignals({ nodes, history, onUpdateNode }: LifeSignalsProps) {
  const readiness = getReadiness(nodes);
  const insights = getWellbeingInsights(nodes, history);
  const todayHistory = history.filter(entry => isToday(entry.timestamp)).sort((a, b) => b.timestamp.localeCompare(a.timestamp));
  const sleepRecorded = todayHistory.some(entry => entry.nodeId === 'sleep');
  return <div className="space-y-4">
    <div className="bg-zinc-950/80 border border-zinc-900 rounded-lg p-4 font-mono flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div><div className="flex items-center gap-2 text-[10px] text-zinc-500 tracking-widest uppercase"><span className="h-2 w-2 rounded-full bg-cyan-400 animate-pulse" />LIVE DAILY STATE</div><h3 className="text-sm font-semibold text-zinc-100 mt-1">Your inputs become a timeline—not a whole-day label.</h3><p className="text-[9px] text-zinc-500 mt-1">Move a slider whenever something changes. Sleep locks after its first entry each day.</p></div><div className="grid grid-cols-2 gap-2 shrink-0"><div className="border border-zinc-900 bg-zinc-900/30 rounded px-4 py-2 text-center"><span className="text-[8px] text-zinc-500 block">CURRENT READINESS</span><strong className={readiness >= 70 ? 'text-emerald-400' : readiness >= 50 ? 'text-amber-400' : 'text-rose-400'}>{readiness}%</strong></div><div className="border border-zinc-900 bg-zinc-900/30 rounded px-4 py-2 text-center"><span className="text-[8px] text-zinc-500 block">CHANGES TODAY</span><strong className="text-cyan-400">{todayHistory.length}</strong></div></div></div>
    <div className="grid grid-cols-1 xl:grid-cols-[minmax(0,2fr)_minmax(320px,1fr)] gap-4 items-start">
      <section className="bg-zinc-950 border border-zinc-900 rounded-lg p-4"><div className="flex justify-between items-center border-b border-zinc-900 pb-2 mb-3"><div className="flex items-center gap-1.5"><Activity className="h-4 w-4 text-cyan-400" /><span className="text-xs font-mono font-bold text-zinc-200 uppercase tracking-wider">How are you feeling now?</span></div><span className="text-[8px] text-zinc-600 font-mono">1 LOW — 10 EXCELLENT</span></div><div className="grid grid-cols-1 md:grid-cols-2 gap-3">{nodes.map(node => { const locked = node.id === 'sleep' && sleepRecorded; const latest = todayHistory.find(entry => entry.nodeId === node.id); return <div key={node.id} className="bg-zinc-900/25 border border-zinc-900 rounded p-3 space-y-2 font-mono"><div className="flex justify-between items-start gap-2"><div><span className="text-[10px] text-zinc-300 uppercase font-bold tracking-wide">{node.label}</span><span className="text-[7px] text-zinc-600 block mt-0.5">{latest ? `LAST CHANGED ${formatEntryTime(latest.timestamp)}` : 'NO CHANGE RECORDED TODAY'}</span></div><span className="text-sm text-white font-bold">{node.value}<span className="text-[8px] text-zinc-600">/10</span></span></div><input aria-label={`${node.label} rating`} type="range" min="1" max="10" step="1" value={node.value} disabled={locked} onChange={event => onUpdateNode(node.id, Number(event.target.value), false)} onPointerUp={event => onUpdateNode(node.id, Number(event.currentTarget.value), true)} onKeyUp={event => onUpdateNode(node.id, Number(event.currentTarget.value), true)} className="w-full h-2 accent-cyan-400 cursor-pointer disabled:cursor-not-allowed disabled:opacity-40" /><DayGraph node={node} entries={history} />{locked && <span className="flex items-center gap-1 text-[7px] text-indigo-400"><LockKeyhole className="h-2.5 w-2.5" />SLEEP IS RECORDED FOR TODAY</span>}</div>; })}</div></section>
      <aside className="space-y-4 xl:sticky xl:top-4"><div className="bg-zinc-950 border border-zinc-900 rounded-lg p-4"><div className="flex items-center gap-1.5 border-b border-zinc-900 pb-2 mb-3"><Brain className="h-4 w-4 text-emerald-400" /><span className="text-xs font-mono font-bold text-zinc-200 uppercase tracking-wider">Useful right now</span></div><div className="space-y-2">{insights.map((insight, index) => <div key={`${insight.title}-${index}`} className={`border rounded p-3 ${insight.tone === 'act' ? 'border-rose-900/60 bg-rose-950/10' : insight.tone === 'watch' ? 'border-amber-900/50 bg-amber-950/10' : 'border-emerald-900/50 bg-emerald-950/10'}`}><strong className="text-[10px] text-zinc-200 block">{insight.title}</strong><p className="text-[9px] text-zinc-500 mt-1 leading-relaxed">{insight.detail}</p></div>)}</div></div><div className="bg-zinc-950 border border-zinc-900 rounded-lg p-4"><div className="flex items-center gap-1.5 border-b border-zinc-900 pb-2 mb-3"><Clock3 className="h-4 w-4 text-cyan-400" /><span className="text-xs font-mono font-bold text-zinc-200 uppercase tracking-wider">Today’s changes</span></div><div className="space-y-2 max-h-64 overflow-y-auto pr-1">{todayHistory.length ? todayHistory.slice(0, 16).map(entry => { const node = nodes.find(item => item.id === entry.nodeId); return <div key={entry.id} className="grid grid-cols-[1fr_auto_auto] gap-3 text-[9px] font-mono border-b border-zinc-900/60 pb-2"><span className="text-zinc-400">{node?.label || entry.nodeId}</span><span className="text-zinc-600">{formatEntryTime(entry.timestamp)}</span><span className="text-cyan-400 font-bold">{entry.value}/10</span></div>; }) : <div className="text-[9px] text-zinc-600 font-mono py-4 text-center"><TrendingUp className="h-5 w-5 mx-auto mb-2" />Move a slider to begin today’s timeline.</div>}</div></div></aside>
    </div>
  </div>;
}
