import { GitHubRepo, VercelProject, SupabaseProject, SystemEvent, Topic, TopicActivity, VideoRecord, Experiment, CreatorInsight } from './types';

export const initialSystemEvents: SystemEvent[] = [];
export const initialGitHubRepos: GitHubRepo[] = [];
export const initialVercelProjects: VercelProject[] = [];

export const initialSupabaseProject: SupabaseProject = {
  id: 'sub-proj-1',
  name: 'content-pipeline',
  status: 'active',
  region: 'default',
  dbVersion: 'Content Engine v1.0',
  tables: [],
  authUsers: [],
  apiLogs: [],
  metrics: {
    dbSize: '0 MB',
    activeConnections: 0,
    cpuUsage: 0,
    memoryUsage: 0,
  },
};

export const initialTopics: Topic[] = [];
export const initialActivities: TopicActivity[] = [];

export const initialVideos: VideoRecord[] = [
  {
    id: 'v-1',
    channelName: 'LearnDriven',
    title: 'How Space-Time Curvature Actually Works',
    videoId: 'space-time-explainer',
    url: 'https://youtube.com/watch?v=space-time-explainer',
    format: 'Long',
    contentType: 'Deep explainer',
    topic: 'Space',
    series: 'Astrophysics Basics',
    category: 'Science',
    pipelineStage: 'Published',
    uploadDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    publishTime: '18:00',
    duration: 620, // 10 min 20 sec
    scriptStatus: 'completed',
    shootStatus: 'completed',
    editStatus: 'completed',
    thumbnailStatus: 'completed',
    scheduleStatus: 'completed',
    publishedStatus: 'completed',
    productionEffortHours: 12.5,
    hookType: 'Question',
    structureType: 'Mechanism',
    contentIntent: 'Educational',
    difficultyLevel: 'hard',
    researchDepth: 'peer-reviewed articles',
    thumbnailVersion: 'v2_dark_neon',
    titleVersion: 'v3_ctr_optimized',
    notes: 'Performed extremely well with core audience. Repeat Space topics.',
    performanceStatus: 'Great',
    tags: {
      topicType: 'Space',
      hookType: 'Question',
      contentStructure: 'Mechanism',
      productionStyle: 'Detailed voiceover + motion graphics',
      audienceIntent: 'Self-education',
      difficulty: 'Hard',
      evergreenPotential: 'High',
      revenuePotential: 'High',
      subscriberPotential: 'High',
      repeatability: 'High'
    },
    metrics: {
      views1h: 1200,
      views3h: 3100,
      views6h: 5400,
      views12h: 8900,
      views24h: 14200,
      views48h: 21000,
      views7d: 38000,
      views28d: 58000,
      lifetimeViews: 62000,
      viewVelocity: 45,
      watchTimeHours: 5166, // 62000 * 5 mins avg / 60
      averageViewDurationSeconds: 300, // 5 mins
      averagePercentageViewed: 48,
      retentionQuality: 'High',
      ctr: 8.4,
      ctrByTrafficSource: {
        'Suggested Videos': 9.2,
        'YouTube Search': 7.8,
        'Browse Features': 8.1
      },
      subscribersGainedPer1kViews: 14.5,
      likesPer1kViews: 42,
      commentsPer1kViews: 6.8,
      sharesPer1kViews: 12.4,
      revenuePer1kViews: 320, // in INR
      revenuePerProductionHour: 1587.2, // 62 * 320 / 12.5
      viewsPerProductionHour: 4960,
      subscribersPerProductionHour: 71.9,
      evergreenScore: 92,
      topicRepeatScore: 88,
      formatEfficiencyScore: 78,
      videoHealthScore: 94,
      watchTimePerImpression: 25.2,
      endScreenPerformance: 12.5,
      completionRate: 48
    }
  },
  {
    id: 'v-2',
    channelName: 'DecodeWorthy',
    title: 'Why the Roman Empire Collapsed (in 60 seconds)',
    videoId: 'roman-collapse-short',
    url: 'https://youtube.com/shorts/roman-collapse-short',
    format: 'Short',
    contentType: 'News decode',
    topic: 'Society',
    series: 'Historical Decodes',
    category: 'History',
    pipelineStage: 'Published',
    uploadDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    publishTime: '17:00',
    duration: 58,
    scriptStatus: 'completed',
    shootStatus: 'completed',
    editStatus: 'completed',
    thumbnailStatus: 'not-applicable',
    scheduleStatus: 'completed',
    publishedStatus: 'completed',
    productionEffortHours: 2.2,
    hookType: 'Contradiction',
    structureType: 'Timeline',
    contentIntent: 'Entertaining',
    difficultyLevel: 'easy',
    researchDepth: 'popular history articles',
    thumbnailVersion: 'default_frame',
    titleVersion: 'v1',
    notes: 'Viral potential hit immediately after Shorts feed push on Day 2.',
    performanceStatus: 'Great',
    tags: {
      topicType: 'Society',
      hookType: 'Contradiction',
      contentStructure: 'Timeline',
      productionStyle: 'Fast cuts + subtitles',
      audienceIntent: 'Curiosity',
      difficulty: 'Easy',
      evergreenPotential: 'Medium',
      revenuePotential: 'Low',
      subscriberPotential: 'High',
      repeatability: 'High'
    },
    metrics: {
      views1h: 300,
      views3h: 700,
      views6h: 1200,
      views12h: 2200,
      views24h: 4100,
      views48h: 15200,
      views7d: 98000,
      lifetimeViews: 105000,
      viewVelocity: 180,
      watchTimeHours: 1400, // 105000 * 48s avg / 3600
      averageViewDurationSeconds: 48,
      averagePercentageViewed: 82.7,
      retentionQuality: 'High',
      ctr: 14.2,
      subscribersGainedPer1kViews: 22.0,
      likesPer1kViews: 95,
      commentsPer1kViews: 11.2,
      sharesPer1kViews: 28.5,
      revenuePer1kViews: 12, // in INR for Shorts
      revenuePerProductionHour: 572.7,
      viewsPerProductionHour: 47727,
      subscribersPerProductionHour: 1050,
      evergreenScore: 45,
      topicRepeatScore: 82,
      formatEfficiencyScore: 95,
      videoHealthScore: 89,
      swipeResistance: 84.5,
      rewatchPotential: 'High',
      completionRate: 81.2
    }
  },
  {
    id: 'v-3',
    channelName: 'LearnDriven',
    title: 'Quantum Computing Mechanics for Members Only',
    videoId: 'quantum-members-explainer',
    url: 'https://youtube.com/watch?v=quantum-members-explainer',
    format: 'Members',
    contentType: 'Practical explainer',
    topic: 'Technology',
    series: 'Members Extra',
    category: 'Tech',
    pipelineStage: 'Published',
    uploadDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    publishTime: '19:00',
    duration: 1250, // 20 min 50 sec
    scriptStatus: 'completed',
    shootStatus: 'completed',
    editStatus: 'completed',
    thumbnailStatus: 'completed',
    scheduleStatus: 'completed',
    publishedStatus: 'completed',
    productionEffortHours: 18.0,
    hookType: 'Danger angle',
    structureType: 'Step-by-step explanation',
    contentIntent: 'High Value',
    difficultyLevel: 'hard',
    researchDepth: 'textbooks + developer SDK docs',
    thumbnailVersion: 'v1',
    titleVersion: 'v2',
    notes: 'Exclusively for Tier 2 members. Highly active comments.',
    performanceStatus: 'Good',
    tags: {
      topicType: 'Technology',
      hookType: 'Danger angle',
      contentStructure: 'Step-by-step explanation',
      productionStyle: 'Screencast + facecam explainer',
      audienceIntent: 'Skill building',
      difficulty: 'Hard',
      evergreenPotential: 'High',
      revenuePotential: 'Medium',
      subscriberPotential: 'Low',
      repeatability: 'Medium'
    },
    metrics: {
      views1h: 50,
      views3h: 150,
      views6h: 280,
      views12h: 420,
      views24h: 680,
      views48h: 1020,
      views7d: 1850,
      lifetimeViews: 3200,
      viewVelocity: 2,
      watchTimeHours: 853,
      averageViewDurationSeconds: 960, // 16 min avg
      averagePercentageViewed: 76.8,
      retentionQuality: 'High',
      ctr: 18.5, // High CTR due to loyal members
      subscribersGainedPer1kViews: 1.2,
      likesPer1kViews: 88,
      commentsPer1kViews: 22.4,
      sharesPer1kViews: 1.5,
      revenuePer1kViews: 1250, // Massive CPM since it is members-only exclusive value
      revenuePerProductionHour: 222.2,
      viewsPerProductionHour: 177.7,
      subscribersPerProductionHour: 0.2,
      evergreenScore: 85,
      topicRepeatScore: 50,
      formatEfficiencyScore: 40,
      videoHealthScore: 86,
      completionRate: 75,
      memberValueScore: 92
    }
  },
  {
    id: 'v-4',
    channelName: 'LearnDriven',
    title: 'The Math behind Black Holes',
    videoId: 'black-hole-math',
    format: 'Long',
    contentType: 'Deep explainer',
    topic: 'Science',
    pipelineStage: 'Edit',
    scriptStatus: 'completed',
    shootStatus: 'completed',
    editStatus: 'in-progress',
    thumbnailStatus: 'pending',
    scheduleStatus: 'pending',
    publishedStatus: 'pending',
    productionEffortHours: 8.5,
    hookType: 'Mystery',
    structureType: 'Comparison',
    difficultyLevel: 'hard',
    notes: 'Blocked because custom 3D animations are rendering slowly.',
    blockedReason: 'Slow rendering of 3D Schwarzschild radius animation',
    nextAction: 'Finish rendering transition clip and merge audio tracks',
    tags: {
      topicType: 'Science',
      hookType: 'Mystery',
      contentStructure: 'Comparison',
      productionStyle: '3D animation + whiteboard',
      audienceIntent: 'Curiosity',
      difficulty: 'Hard',
      evergreenPotential: 'High',
      revenuePotential: 'High',
      subscriberPotential: 'Medium',
      repeatability: 'Medium'
    }
  },
  {
    id: 'v-5',
    channelName: 'DecodeWorthy',
    title: 'How algorithms spy on you',
    videoId: 'algorithm-spying-short',
    format: 'Short',
    contentType: 'Myth-busting',
    topic: 'Technology',
    pipelineStage: 'Script',
    scriptStatus: 'in-progress',
    shootStatus: 'pending',
    editStatus: 'pending',
    thumbnailStatus: 'not-applicable',
    scheduleStatus: 'pending',
    publishedStatus: 'pending',
    productionEffortHours: 1.5,
    hookType: 'Shocking fact',
    structureType: 'Cause effect',
    difficultyLevel: 'medium',
    nextAction: 'Write the hook segment focusing on smartphone mic triggers',
    tags: {
      topicType: 'Technology',
      hookType: 'Shocking fact',
      contentStructure: 'Cause effect',
      productionStyle: 'B-roll overlay + green screen',
      audienceIntent: 'Awareness',
      difficulty: 'Medium',
      evergreenPotential: 'High',
      revenuePotential: 'Low',
      subscriberPotential: 'High',
      repeatability: 'High'
    }
  },
  {
    id: 'v-6',
    channelName: 'LearnDriven',
    title: '10 System Concepts You Must Know',
    videoId: 'systems-concepts-long',
    format: 'Long',
    contentType: 'Practical explainer',
    topic: 'Systems',
    pipelineStage: 'Schedule',
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(), // due in 2 days
    publishTime: '18:00',
    scriptStatus: 'completed',
    shootStatus: 'completed',
    editStatus: 'completed',
    thumbnailStatus: 'completed',
    scheduleStatus: 'completed',
    publishedStatus: 'pending',
    productionEffortHours: 9.0,
    hookType: 'Money angle',
    structureType: 'Timeline',
    difficultyLevel: 'medium',
    nextAction: 'Auto-publish on schedule date',
    tags: {
      topicType: 'Systems',
      hookType: 'Money angle',
      contentStructure: 'Timeline',
      productionStyle: 'Screencast + voiceover',
      audienceIntent: 'Skill building',
      difficulty: 'Medium',
      evergreenPotential: 'High',
      revenuePotential: 'Medium',
      subscriberPotential: 'Medium',
      repeatability: 'High'
    }
  },
  {
    id: 'v-7',
    channelName: 'LearnDriven',
    title: 'Why Inflation is Not What You Think',
    videoId: 'inflation-myths',
    url: 'https://youtube.com/watch?v=inflation-myths',
    format: 'Long',
    contentType: 'Myth-busting',
    topic: 'Finance',
    pipelineStage: 'Published',
    uploadDate: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
    publishTime: '18:00',
    duration: 540,
    scriptStatus: 'completed',
    shootStatus: 'completed',
    editStatus: 'completed',
    thumbnailStatus: 'completed',
    scheduleStatus: 'completed',
    publishedStatus: 'completed',
    productionEffortHours: 7.0,
    hookType: 'Myth vs reality',
    structureType: 'Comparison',
    difficultyLevel: 'medium',
    notes: 'Initial CTR was poor (3.2%), but boosted to 6.8% after changing thumbnail to red background.',
    performanceStatus: 'Normal',
    tags: {
      topicType: 'Finance',
      hookType: 'Myth vs reality',
      contentStructure: 'Comparison',
      productionStyle: 'Facecam + graphics overlay',
      audienceIntent: 'Self-education',
      difficulty: 'Medium',
      evergreenPotential: 'High',
      revenuePotential: 'High',
      subscriberPotential: 'Medium',
      repeatability: 'Medium'
    },
    metrics: {
      views1h: 400,
      views3h: 900,
      views6h: 1500,
      views24h: 3200,
      views48h: 5100,
      views7d: 12000,
      views28d: 22000,
      lifetimeViews: 23200,
      viewVelocity: 5,
      watchTimeHours: 1933,
      averageViewDurationSeconds: 300,
      averagePercentageViewed: 55.5,
      retentionQuality: 'Medium',
      ctr: 6.8,
      subscribersGainedPer1kViews: 8.5,
      likesPer1kViews: 35,
      commentsPer1kViews: 4.2,
      sharesPer1kViews: 6.5,
      revenuePer1kViews: 280,
      revenuePerProductionHour: 928,
      viewsPerProductionHour: 3314,
      subscribersPerProductionHour: 28.1,
      evergreenScore: 82,
      topicRepeatScore: 68,
      formatEfficiencyScore: 70,
      videoHealthScore: 75,
      watchTimePerImpression: 18.2,
      endScreenPerformance: 6.2,
      completionRate: 51.5
    }
  },
  {
    id: 'v-8',
    channelName: 'DecodeWorthy',
    title: 'The Game Theory of Climate Change',
    videoId: 'climate-game-theory-short',
    url: 'https://youtube.com/shorts/climate-game-theory-short',
    format: 'Short',
    contentType: 'Practical explainer',
    topic: 'Science',
    pipelineStage: 'Published',
    uploadDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    publishTime: '17:00',
    duration: 55,
    scriptStatus: 'completed',
    shootStatus: 'completed',
    editStatus: 'completed',
    thumbnailStatus: 'not-applicable',
    scheduleStatus: 'completed',
    publishedStatus: 'completed',
    productionEffortHours: 1.8,
    hookType: 'Question',
    structureType: 'Problem solution',
    difficultyLevel: 'medium',
    notes: 'Low swipe resistance resulted in early stalling on the Shorts shelf.',
    performanceStatus: 'Watch',
    tags: {
      topicType: 'Science',
      hookType: 'Question',
      contentStructure: 'Problem solution',
      productionStyle: 'Fast cuts + B-roll',
      audienceIntent: 'Curiosity',
      difficulty: 'Medium',
      evergreenPotential: 'Low',
      revenuePotential: 'Low',
      subscriberPotential: 'Medium',
      repeatability: 'High'
    },
    metrics: {
      views1h: 450,
      views3h: 1200,
      views6h: 1800,
      views12h: 2100,
      views24h: 2400,
      views48h: 2500,
      views7d: 2650,
      lifetimeViews: 2650,
      viewVelocity: 0.1,
      watchTimeHours: 18.4,
      averageViewDurationSeconds: 25,
      averagePercentageViewed: 45.4,
      retentionQuality: 'Low',
      ctr: 5.2,
      subscribersGainedPer1kViews: 2.1,
      likesPer1kViews: 15,
      commentsPer1kViews: 0.8,
      sharesPer1kViews: 1.2,
      revenuePer1kViews: 10,
      revenuePerProductionHour: 14.7,
      viewsPerProductionHour: 1472,
      subscribersPerProductionHour: 3.1,
      evergreenScore: 10,
      topicRepeatScore: 30,
      formatEfficiencyScore: 45,
      videoHealthScore: 28,
      swipeResistance: 48.2, // stalled
      rewatchPotential: 'Low',
      completionRate: 35.5
    }
  }
];

export const initialExperiments: Experiment[] = [
  {
    id: 'exp-1',
    name: 'Contradiction Hooks vs Question Hooks',
    hypothesis: 'Contradiction hooks on DecodeWorthy Shorts will improve swipe resistance by at least 15% and initial velocity by 2x.',
    startDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    videosIncluded: ['roman-collapse-short', 'climate-game-theory-short'],
    metricBeingTested: 'Swipe Resistance (%)',
    result: 'Contradiction hook achieved 84.5% swipe resistance. Question hook achieved 48.2% swipe resistance. Contradiction hooks performed significantly better.',
    decision: 'Standardize contradiction hooks for all short history/society decodes.',
    learning: 'Viewers scrolling the Shorts shelf respond 2x faster to bold myths or contradictions rather than general questions.',
    status: 'completed'
  },
  {
    id: 'exp-2',
    name: 'Deep Green vs Bright Purple Thumbnails',
    hypothesis: 'Deep green/emerald themes will yield 20% higher CTR for LearnDriven astrophysics decodes than our traditional bright purple neon theme.',
    startDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    videosIncluded: ['space-time-explainer'],
    metricBeingTested: 'Click-Through Rate (CTR)',
    status: 'active'
  }
];

export const initialCreatorInsights: CreatorInsight[] = [
  {
    id: 'ins-1',
    title: 'High Conversion Potential',
    description: 'Your contradiction hooks are outperforming question hooks by 75% on DecodeWorthy Shorts. Standardize this style.',
    type: 'success',
    channel: 'DecodeWorthy',
    reason: 'Experiment "Contradiction Hooks vs Question Hooks" showed a 36.3% higher swipe resistance on contradiction hooks.',
    actionLabel: 'Use Contradiction Hooks'
  },
  {
    id: 'ins-2',
    title: 'Packaging Underperformance',
    description: 'The video "Why Inflation is Not What You Think" has high retention (55.5%) but normal CTR (6.8%). Changing title/thumbnail is recommended.',
    type: 'warning',
    channel: 'LearnDriven',
    reason: 'CTR is 18% lower than your channel average for long-form finance topics, but AVD is in the top tier.',
    actionLabel: 'Change Thumbnail'
  },
  {
    id: 'ins-3',
    title: 'Topic Expansion Opportunity',
    description: 'Space explainer "How Space-Time Curvature Actually Works" achieved high view velocity (45 v/h) and generated 14.5 subscribers per 1,000 views.',
    type: 'recommendation',
    channel: 'LearnDriven',
    reason: 'Astrophysics topics are yielding a 2.4x higher subscriber conversion rate than average, with strong evergreen potential (score: 92).',
    actionLabel: 'Repeat Space Topic'
  },
  {
    id: 'ins-4',
    title: 'Upload Consistency Risk',
    description: 'Your LearnDriven channel has no scheduled uploads remaining after the next 2 days. The content buffer is critical.',
    type: 'warning',
    channel: 'LearnDriven',
    reason: 'Zero scheduled videos left in pipeline after "10 System Concepts You Must Know" goes live in 48 hours.',
    actionLabel: 'Schedule Next Video'
  }
];

